//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VajaBazeIndividualno.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Dijak
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dijak()
        {
            this.DijakPodročje = new HashSet<DijakPodročje>();
            this.IzvedbaDijak = new HashSet<IzvedbaDijak>();
            this.PlanDijak = new HashSet<PlanDijak>();
        }

        [Display(Name = "ID Dijaka")]
        public int DijID { get; set; }
        [Display(Name = "Ime")]
        public string DijIme { get; set; }
        [Display(Name = "Priimek")]
        public string DijPriimek { get; set; }
        [Display(Name = "Razred")]
        public string DijRazred { get; set; }
        [DisplayFormat (DataFormatString ="{0:dd.MM.yyyy}")]
        [Display(Name = "Datum Rojstva")]
        public Nullable<System.DateTime> DijDatumRojstva { get; set; }
        public byte[] DijaSlika { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}")]
        [Display(Name = "Nad Datum")]
        public Nullable<System.DateTime> DijIDNadDatum { get; set; }
        [Display(Name = "Nad Ustanova")]
        public string DijIDNadUstanova { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}")]
        [Display(Name = "Nad Potrditev")]
        public Nullable<System.DateTime> DijIDNadPotrditev { get; set; }
        [Display(Name = "Mati")]
        public string DijMati { get; set; }
        [Display(Name = "Oče")]
        public string DijOče { get; set; }
        [Display(Name = "User ID")]
        public Nullable<System.Guid> UserID { get; set; }

        [Display(Name = "Razredniki")]
        public virtual Razredniki Razredniki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(Name = "Dijak Področje")]
        public virtual ICollection<DijakPodročje> DijakPodročje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(Name = "Izvedba Dijak")]
        public virtual ICollection<IzvedbaDijak> IzvedbaDijak { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(Name = "Plan Dijak")]
        public virtual ICollection<PlanDijak> PlanDijak { get; set; }
    }
}
